### ISSUE TITLE
Server crash on startup

### ISSUE THREAD

**Issue by Milii20** [AzazeII/Applied-Integrations#12]
**Describe the bug**
i added the mod into my modpack

**To Reproduce**
add the mod (probably i am doing something wrong, but i cant figure it out)

**Expected behavior**
minecraft server starting?

**Enviroment**
 - every version for 1.12.2, not happening on 1.7.10, last one tried was 8.0.9.1 (which's file name is AppliedIntegrations-1.12.2-Alpha-8.0.8.1)
 - appliedenergistics2-rv6-stable-6
 - forge-1.12.2-14.23.5.2814-universal

**Additional context**
https://pastebin.com/0sPV6kHs

**Comment by indiscrete-void** [comment]
Ohh.. Of course it will not start on server, item from line 59 registering renderer ;(.
I will fix this issue in new version

**Comment by indiscrete-void** [comment]
Fixed https://minecraft.curseforge.com/projects/applied-integrations/files/2694568

**Comment by Milii20** [comment]
Thank you!, that problem is fixed, but now i seem to get another crash only on my server when i add the mod, maybe you can help me?

https://pastebin.com/YSPuqHwr
