### ISSUE TITLE
New Server Crash on Startup

### ISSUE THREAD

**Issue by Milii20** [AzazeII/Applied-Integrations#13]
Thank you!, the other problem is fixed, but now i seem to get another crash only on my server when i add the mod, maybe you can help me?

https://pastebin.com/YSPuqHwr

Nothing has changed, same modpack, but i have the new version of Applied Integrations (8.0.9.2), tried with the old versions and still nothing, and removing applied integrations fixes the crash

**Comment by indiscrete-void** [comment]
It's pretty hard to resolve the issue in modpack with 437 mods loaded. This issue is happening only with your modpack, means some of mods are changing mechanics of loading some stuff from AE2, or something like this. Please try to reproduce this issue with only AE2 and AI, if issue still happens, then this is server-specific issue. I tested modpack with only AE2 and AI, and no issue happened

**Comment by Milii20** [comment]
i will do, once i have an answer i will edit this

**Comment by Milii20** [comment]
Greetings!, since i aparently have problems to edit the last comment i made i will just make a new comment, 
i started my tests with a new tiny modpack, starting from only AI and AE and JEI, and then adding mods until i got the crash (https://pastebin.com/fMPWub1e), i can safely say the problem is some weird interaction between AI and spatialservermod-1.3 (https://minecraft.curseforge.com/projects/spatialcompat) since both servers, the one with the small modpack and the 437 mods one started and worked perfectly as soon as i removed one of them, AI or SpatialCompat

**Comment by indiscrete-void** [comment]
Thank you for this report, i will try to fix this bug

**Comment by indiscrete-void** [comment]
Issue fixed, wait for 8.0.10.1 version on curseforge.
Thank you for resolving conflict mod. Good luck!

**Comment by Milii20** [comment]
Thank you for fixing it so fast!

**Comment by indiscrete-void** [comment]
Also, if you'll have more issue, there is my discord server link:
https://discord.gg/eC7JpZe
