### ISSUE TITLE
Crash when placing a block next to Server Core

### ISSUE THREAD

**Issue by Akaruz64** [AzazeII/Applied-Integrations#14]
**Describe the bug**
I'm not really sure, since VanillaFix wont let the CTD actually happen, but i'm pretty sure this isn't supposed to happen, hope it helps, if you need i can try in a clean world with only a few mods.

**To Reproduce**
Place a Server Core

**Expected behavior**
Place server core without any CTD

**Enviroment**
 - Lates 1.12.2 Alpha
 - RV6
 - 2824

https://paste.dimdev.org/fahizadexo.mccrash

**Comment by indiscrete-void** [comment]
Thank you for response. Wait for new version, i'm working on relatively big update, this bug will be fixed

**Comment by indiscrete-void** [comment]
Also, from log we have: `    at AppliedIntegrations.Blocks.MEServer.BlockServerCore.onBlockActivated(BlockServerCore.java:59)
`

Means tile was clicked. Nothing special, i just written new handler, and tile trying to open gui with previous xD

**Comment by AzazeII** [comment]
Webhook comment test
