### ISSUE TITLE
energy import and export busses not working at all

### ISSUE THREAD

**Issue by supremedutchgamer** [AzazeII/Applied-Integrations#16]
quite simply put, neither the energy input nor export bus works. the storage bus seems to work fine as long as the cell hooked up to the network is not empty, otherwise checking the energy terminal will get you kicked out of the world

might be a cross-mod issue, but in my case: rebuild the same thing shown below at screenshots, the blue energy cells wont charge from the creative energy cell despite being hooked up

the expected behaviour would be that the import bus would import the energy, which would then be stored in the energy storage cells. and also output to the energy cells on the right.

**Screenshot**
https://imgur.com/a/p9KeRIj

**Enviroment**
 - applied integrations beta 8.0.14.1
 - Applied energistics 2 RV6 stable 6
 - forge 14.23.5.2838

**Additional context**
i also have extracells and thaumic energistics installed. as well as AE2 wireless terminal and spatialservermod.

**Comment by BobVonBob** [comment]
They do  work, but filtering is mandatory and as far as I can tell can't be done without an item powered by the energy type you want to import/export.

**Comment by indiscrete-void** [comment]
Import bus should also work without filtering. Do you running separate client and server ?

**Comment by indiscrete-void** [comment]
>otherwise checking the energy terminal will get you kicked out of the world

Check latest.log for errors, if it contains any, then you can provide it instead of crashlog

**Comment by indiscrete-void** [comment]
Also, your energy cell on other side of connector pair isn't configure to output any energy
![Screenshot 2019-06-25 at 13 10 32](https://user-images.githubusercontent.com/32298517/60090162-aac63000-974a-11e9-9f5f-6f432b337c1f.png)

**Comment by indiscrete-void** [comment]
Currently cannot reproduce this issue with CoFH mods, since curse network is down:
![Screenshot 2019-06-25 at 13 25 08](https://user-images.githubusercontent.com/32298517/60091312-efeb6180-974c-11e9-9261-bf624e975e04.png)

But i reproduced your structure with immersive engineering equivalents(which is as far as i can tell equal on code mechanics level to CoFH cells) and everything is working fine:
![Screenshot 2019-06-25 at 13 24 31](https://user-images.githubusercontent.com/32298517/60091329-fbd72380-974c-11e9-82a9-6893090cd14b.png)

**Comment by BobVonBob** [comment]
I built a minimal non-working setup, just JEI, Thermal, and AI loaded, plus dependencies.
![image](https://user-images.githubusercontent.com/34696418/60126325-5bd0c880-9753-11e9-9f76-97f5d3f47ff4.png)
![image](https://user-images.githubusercontent.com/34696418/60126375-75721000-9753-11e9-9163-56dc798b558f.png)
![image](https://user-images.githubusercontent.com/34696418/60126440-9cc8dd00-9753-11e9-83d4-fe5b1cf707c3.png)

**Comment by indiscrete-void** [comment]
Finally reproduced issue. Wait for new version for fix

**Comment by indiscrete-void** [comment]
Export bus is working fine with energy cells from thermal in my testing world
