### ISSUE TITLE
Bug: Infinite Energy

### ISSUE THREAD

**Issue by BohneMPs** [AzazeII/Applied-Integrations#19]
If you put an Energy Import Bus onto an EnderIO Capacitor Bank with energy inside it, the Import Bus puts energy into the storage cells, but doesn't empty the Capacitor Bank.

 - Mod version: 1.12.2-3cd3ad3c
 - Applied energistics 2 version: rv6-stable-7
 - Forge version: 14.23.5.2847

**Comment by indiscrete-void** [comment]
Reproduced the issue. Seams like it's another issue that caused by enderio energy storage capability wrapper. I'll try to fix this issue later.
