### ISSUE TITLE
ME Pattern Encoder whis 16 slots for crafting

### ISSUE THREAD

**Issue by Camperhelpme** [AzazeII/Applied-Integrations#2]
I apologize in advance sorry for my bad English. But the thing is i wanted to ask you can you help me create a block similar to ME Pattern Encoder whis 16 slots for crafting . In the mod gregtech exist multiblock structure Assembly line and it used 16 slots for craft . I can't create autocraft because i have 9 slot instead of 16 . I would very much if you helped me.
![2019-01-28_17 35 24](https://user-images.githubusercontent.com/47112701/51845188-1638dc80-2328-11e9-9b14-42c468a1e849.png)

**Comment by AzazeII** [comment]
i'm not sure I added this in the near future. I have too many things to fix, but maybe later i will add this feature

**Comment by indiscrete-void** [comment]
I don't sure if this mod can help you, but i recommend to check it out:
https://minecraft.curseforge.com/projects/packagedauto
