### ISSUE TITLE
ME Export Bus

### ISSUE THREAD

**Issue by WardenCommander** [AzazeII/Applied-Integrations#22]
**Describe the bug**
Export Bus doesn't export EU power to a ic2 machine

**Enviroment**
 - Forge 1.12.2 - 14.23.5.2838
 - appliedenergistics2-rv6-stable-7
 - this mod latest version

could you please take a look?

**Comment by indiscrete-void** [comment]
Cannot reproduce the original issue. However when i was trying to put EU in filter of export bus in order for it to work i got crash. Did you put EU-containing item/block in filter of export bus when got this issue ? If no, then it's not issue but intended mechanic, since item export bus also doesn't export anything until you specify item in filter

**Comment by indiscrete-void** [comment]
Now it's not crashing but also don't put energy, so original issue occurs

**Comment by indiscrete-void** [comment]
https://www.curseforge.com/minecraft/mc-mods/applied-integrations/files/2847400

**Comment by WardenCommander** [comment]
when i put EU equipment in filter it shows EU, but when i exit ME Energy export bus and enter again
it takes 2-3 seconds for filter to show EU energy

![p3](https://user-images.githubusercontent.com/46477089/71520702-a6c3c800-28bd-11ea-84a3-9b00dcd1c279.png)

Export bus still not exporting EU energy to a machine

**Comment by indiscrete-void** [comment]
This behaviour with filter showing after some delay is intended for optimisation. 
About export bus not exporting energy to EU, last time i checked it was working just fine(on MFSU). On what machine you was testing export bus ?

**Comment by indiscrete-void** [comment]
And yeah... This really doesn't work with anything not implementing IEnergyStorage class from IC2 (e.g MFSU)

**Comment by WardenCommander** [comment]
I tested on compressor

**Comment by indiscrete-void** [comment]
Have no clue why MFSU implements IEnergyStorage but compressor or other producing machines implement other class. Anyway only thing i need is to add other class to list of classes of machines with EU energy support 😸

**Comment by WardenCommander** [comment]
Thanx will have a look 👍  could you update curseforge please

**Comment by indiscrete-void** [comment]
Later, i'll fix other issue from you with terminal and update CF version
