### ISSUE TITLE
ME Energy Terminal

### ISSUE THREAD

**Issue by WardenCommander** [AzazeII/Applied-Integrations#23]
**Describe the bug**
ME Energy terminal not showing correct energy level in Cell/s

**To Reproduce**
Steps to reproduce the behavior

**Enviroment**
Forge 1.12.2 - 14.23.5.2838
appliedenergistics2-rv6-stable-7
this mod latest version

![p1](https://user-images.githubusercontent.com/46477089/71520548-fd7cd200-28bc-11ea-9485-30ab1160a63a.png)

![p2](https://user-images.githubusercontent.com/46477089/71520554-01105900-28bd-11ea-9f81-81343f36eeae.png)

EDIT: after few minutes its showing normally... but not in Real time, you need to exit Terminal and enter again to update value
EDIT: energy in cell is updated in real time

**Comment by WardenCommander** [comment]
UPDATE: also interface dont charge EU equipment, and if you leave equipment in interface and close interface it will destroy/delete equipment

![p4](https://user-images.githubusercontent.com/46477089/71520868-96601d00-28be-11ea-89cb-091aea762709.png)

**Comment by indiscrete-void** [comment]
The first issue with incorrect energy amount is probably caused by that fact energy terminal GUI **adds** current energies list into it's client-sided list. So energy grows forever when it's added. Probably only need to replace add with set

**Comment by indiscrete-void** [comment]
https://www.curseforge.com/minecraft/mc-mods/applied-integrations/files/2851681
