### ISSUE TITLE
[1.12.2-a6] Crashes without IC2

### ISSUE THREAD

**Issue by BrisingrAerowing** [AzazeII/Applied-Integrations#4]
[Crash Log](https://paste.dimdev.org/ifesobahox.mccrash)

It looks like an \@Optional.Interface is missing somewhere. Or is IC2 supposed to be a required dependency?

**Comment by AzazeII** [comment]
No IC2 is not required dependency for this mod. Thank you for this report,
RV6(1.12.2) branch is currently in Alpha version, and crashes like these is not rare.
I don't think it caused by IC2, because my current testing modpack doesn't have IC2 at all, i'll try to fix this issue

**Comment by AzazeII** [comment]
Fixed this issue in 8.0.1 update
