### ISSUE TITLE
Weird Items (therminal/p2p and more)

### ISSUE THREAD

**Issue by TheSnowyChickens** [AzazeII/Applied-Integrations#6]
Some wrong Items / item names^^
![grafik](https://user-images.githubusercontent.com/29357962/54084804-b9244380-4335-11e9-8207-a59f6b76d4f1.png)

![grafik](https://user-images.githubusercontent.com/29357962/54084809-c5100580-4335-11e9-8f56-121e10c96feb.png)

Summary from all "wrong" item names:
![Zusammenfassung](https://user-images.githubusercontent.com/29357962/54084963-5da78500-4338-11e9-89d2-968aa9729b8c.png)

MC: 1.12.2
Forge: 2815
AE: rv6-stable 6
AI: Alpha 7 / 8.0.5

**Comment by AzazeII** [comment]
I know that these items has no localization. Storage components not even used for crafting in 1.12.2 version, and i'm not currently written localization for storage components. Same for mana formation and annihilation core. EmberP2PItemPart is not working item at all, same for terminal. Localization will be done in 8.0.6 version

**Comment by TheSnowyChickens** [comment]
@AzazeII 
Before I open a new issue: is it known, that the "ME Server Core" let the game crash ?
https://paste.dimdev.org/nejilamitu.mccrash

(I only wanted to place him on the ground)
:_=)
