### ISSUE TITLE
Crash with minimum 2 blocks

### ISSUE THREAD

**Issue by TheSnowyChickens** [AzazeII/Applied-Integrations#7]
Hi,
I found some crashes:
1. Server security Terminal
https://paste.dimdev.org/kolijucule.mccrash

2. Server Core:
https://paste.dimdev.org/nejilamitu.mccrash
(I placed both blocks on the ground -> world is corrupted)

MC: 1.12.2
Forge: 2815
AE: Rv6-Stable 6
AI: 8.0.5
RFAPI: 2.1.0.6

(the following stuff *should* be known)
![2019-03-11_23 42 43](https://user-images.githubusercontent.com/29357962/54163007-e537e580-4457-11e9-8273-e83c9d926df3.png)
(all 4 logic blocks)

Ps: I saw in the curse comments, that someone had crashes too, I hope these 2 kinds of crash are not the same.

**Comment by AzazeII** [comment]
Thank you for this report, this crash will be fixed in new version. If you will try to use energy import/export bus, and it will give crash, don't create new issue in tracker, because all the parts(buses) are not working yet(except for interface), and these buses will probably give crash.

**Comment by TheSnowyChickens** [comment]
kk
