### ISSUE TITLE
it crashes my 1.7.10 server

### ISSUE THREAD

**Issue by duzholger** [AzazeII/Applied-Integrations#8]
I can't get it to work with my server it a 1.7.10 server
[crash-2019-03-16_01.12.57-server.txt](https://github.com/AzazeII/Applied-Integrations/files/2973288/crash-2019-03-16_01.12.57-server.txt)

**Comment by AzazeII** [comment]
Will be fixed on new 1.7.10 version, it's know bug, since 1.12.2 also had this bug in first alpha

**Comment by duzholger** [comment]
when can we get a fix?

**Comment by AzazeII** [comment]
There is new version: https://minecraft.curseforge.com/projects/applied-integrations/files/2688012
